#!/usr/bin/env python

from pip._internal import main as pip
pip(['install', '--upgrade', 'pip'])
pip(['install', '--user', 'pandas'])
pip(['install', '--user', 'numpy'])
pip(['install', '--user', 'sklearn'])
pip(['install', '--user', 'catboost'])
pip(['install', '--user', 'pyarrow'])
pip(['install', '--upgrade', 'os'])
pip(['install', '--upgrade', 'sys'])
pip(['install', '--upgrade', 'site'])
pip(['install', '--upgrade', 'pyodbc'])
pip(['install', '--upgrade', 'imp'])
pip(['install', '--upgrade', 'yaml'])
pip(['install', '--upgrade', 'matplotlib'])
pip(['install', '--upgrade', 'dateutil'])
pip(['install', '--upgrade', 'datetime'])
pip(['install', '--upgrade', 'pylab'])
pip(['install', '--upgrade', 'copy'])
pip(['install', '--upgrade', 'pathlib'])
pip(['install', '--upgrade', 'shap'])
